# @generated by nix/resolve.py -- do not edit
# Load-time mirror of nix/lock.json (Starlark cannot read JSON at
# load/analysis time). PATHS urls are absolute; sha256 is the
# NarHash as hex (snix serves uncompressed NARs, so buck2's native
# download_file verifies the NarHash itself).

PACKAGES = {
    "bash": {
        "storePath": "/nix/store/0641h8qfqaxnwrsw2nzrz6i1wbzyx92l-bash-interactive-5.3p9",
        "outputs": {
            "debug": "/nix/store/l76krav3w28kmd2b00lb687i1ykswvp0-bash-interactive-5.3p9-debug",
            "dev": "/nix/store/44fi33grmrbkp2h80a31mqj5lqd3qfwp-bash-interactive-5.3p9-dev",
            "doc": "/nix/store/5j2akpmlk107gzdqkms35r3nwhkwnibh-bash-interactive-5.3p9-doc",
            "info": "/nix/store/pspjmjsphdkjsi20gpxh2p1aq6p73n1c-bash-interactive-5.3p9-info",
            "man": "/nix/store/b67fr4nba948zxxpmdsnzqr06l9fnnag-bash-interactive-5.3p9-man",
            "out": "/nix/store/0641h8qfqaxnwrsw2nzrz6i1wbzyx92l-bash-interactive-5.3p9",
        },
    },
    "coreutils": {
        "storePath": "/nix/store/sr26flm2nkfa12dkrwj2630kqsfakky4-coreutils-9.11",
        "outputs": {
            "debug": "/nix/store/wifadx5v4ps5nvf23cr22lswn3q70s6f-coreutils-9.11-debug",
            "info": "/nix/store/zs5bzwnkhgzka1ccvzkhx0xzf1mlah2j-coreutils-9.11-info",
            "out": "/nix/store/sr26flm2nkfa12dkrwj2630kqsfakky4-coreutils-9.11",
        },
    },
    "gcc": {
        "storePath": "/nix/store/xcnqqnhw9hb4j5rjgds2yjryi8qki5f3-gcc-wrapper-15.2.0",
        "outputs": {
            "info": "/nix/store/pcar1vqvmn2y42lplzca392yx605kk31-gcc-wrapper-15.2.0-info",
            "man": "/nix/store/dxqah042znlglapf07vha4qannacibf2-gcc-wrapper-15.2.0-man",
            "out": "/nix/store/xcnqqnhw9hb4j5rjgds2yjryi8qki5f3-gcc-wrapper-15.2.0",
        },
    },
    "ghc": {
        "storePath": "/nix/store/61a2wc7hwqg7mqb88g3n1l276zsyrx45-ghc-9.10.3",
        "outputs": {
            "doc": "/nix/store/d82g4qdgarx0rxbmgf9k68pr5135y1h6-ghc-9.10.3-doc",
            "out": "/nix/store/61a2wc7hwqg7mqb88g3n1l276zsyrx45-ghc-9.10.3",
        },
    },
    "hello": {
        "storePath": "/nix/store/nm7p8wxflggcwxfzayhysq4z6a1wg373-hello-2.12.3",
        "outputs": {
            "out": "/nix/store/nm7p8wxflggcwxfzayhysq4z6a1wg373-hello-2.12.3",
        },
    },
    "openssl": {
        "storePath": "/nix/store/clvbx203wyqkdnqc5ngyhjlhcqn5s9x9-openssl-3.6.2-bin",
        "outputs": {
            "bin": "/nix/store/clvbx203wyqkdnqc5ngyhjlhcqn5s9x9-openssl-3.6.2-bin",
            "debug": "/nix/store/029b2avw85i19v6vvxvrrx15kmg29kpr-openssl-3.6.2-debug",
            "dev": "/nix/store/i0jqva96qfgc76g8w7jbyiv6h3si07b9-openssl-3.6.2-dev",
            "doc": "/nix/store/32xivk30pdrnhhn2774dha3xphwcgb2v-openssl-3.6.2-doc",
            "man": "/nix/store/0wv0fnqsp138dln7cx229hlf8qm553p5-openssl-3.6.2-man",
            "out": "/nix/store/l0vl4dali2mvbpi30a8da1f71jl85myg-openssl-3.6.2",
        },
    },
    "python3": {
        "storePath": "/nix/store/l9k0anq0z7zz81zcwy035jfwap9ga6rl-python3-3.13.13",
        "outputs": {
            "debug": "/nix/store/g2pg1an3v5pm2fmwg1g7dw77ddpqirg7-python3-3.13.13-debug",
            "out": "/nix/store/l9k0anq0z7zz81zcwy035jfwap9ga6rl-python3-3.13.13",
        },
    },
    "strace": {
        "storePath": "/nix/store/afkryhd3wfa29958lc3b1fxjxb60zl6k-strace-7.1",
        "outputs": {
            "debug": "/nix/store/9nw5g4mx5aghc7rz5viz7ilx3l71qyl8-strace-7.1-debug",
            "man": "/nix/store/67gd1jz8fp4pqb09wws80z9jykx8ykd0-strace-7.1-man",
            "out": "/nix/store/afkryhd3wfa29958lc3b1fxjxb60zl6k-strace-7.1",
        },
    },
}

PATHS = {
    "/nix/store/009gwlbgzg0ybil10v0q56gpgyvsi3wr-libpsl-0.21.5": {
        "nar_size": 117608,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/ipz4lbivx3q7gr79130d6g5ix35vibnw-libunistring-1.4.2",
            "/nix/store/qjxwvydl5f07l8zgg6p2pyypll8ybc9n-publicsuffix-list-0-unstable-2026-05-13",
            "/nix/store/zlvydh6q1rv1jza79b21yhi07ic0dkkg-libidn2-2.3.8",
        ],
        "sha256": "b8c137b666dc443ceb1d94f3d1895a8d20499d3e343b1274099b3685efe73090",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIME4FVad8o3eO3d4p3HlynxtQ2vNvGQ3vBhQlMmVIqhuGBY?narsize=117608",
    },
    "/nix/store/029b2avw85i19v6vvxvrrx15kmg29kpr-openssl-3.6.2-debug": {
        "nar_size": 12378528,
        "references": [
            "/nix/store/c2d7chn37a4q79xby5k12kcdqa905vnl-openssl-3.6.2.tar.gz",
            "/nix/store/clvbx203wyqkdnqc5ngyhjlhcqn5s9x9-openssl-3.6.2-bin",
            "/nix/store/k7kxg101ikkm0cyf8jcqhg948vy542af-perl-5.42.0",
            "/nix/store/l0vl4dali2mvbpi30a8da1f71jl85myg-openssl-3.6.2",
            "/nix/store/zh1ijdhb6gng1509b1zrilb6xlzx60j6-bash-5.3p9",
        ],
        "sha256": "27755ce37561909f5acba330a5408bb4e88b6afde0088b393efcd7d7fe5879d2",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIPhp8sSvIhBuRsVmmfa8n0igm9CFgLSmVVf7ieVIVWRIGMAB?narsize=12378528",
    },
    "/nix/store/0641h8qfqaxnwrsw2nzrz6i1wbzyx92l-bash-interactive-5.3p9": {
        "nar_size": 7415800,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/im7mcigg1x2bq9rg7z3h3i26pjmss0c7-readline-8.3p3",
            "/nix/store/mxq1r9w2w2y9lsqb5fkcyb5xbbki1n57-ncurses-6.6",
        ],
        "sha256": "eb45280b883ec0ee74fc5a13502a5736e3f52174b7da6acdd5c813da8c6b2633",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIATh-lHQ2Dp92sJJfOGg0-s8mLizwHc0z3OtQ953fwSUGNoC?narsize=7415800",
    },
    "/nix/store/08nfpyc4qhzdkc37nznvfpbybihyr063-attr-2.5.2": {
        "nar_size": 92720,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "64b86233339c3d8631d1e8934c8b58cf283d8b98534ee154901c224da13c45f4",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIL2UhCvxH4q2my9gdVRGZ7J4LwICM_dyLpZ8-CD27oFzGFQ?narsize=92720",
    },
    "/nix/store/0wv0fnqsp138dln7cx229hlf8qm553p5-openssl-3.6.2-man": {
        "nar_size": 4113912,
        "references": [
        ],
        "sha256": "db143fdf66e8305ddc85984f7d4bc8deabfc144a6466e24841097a43e9e56630",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIDAbkS2Rp2eLfRDLF9WDUnJf4A_k3cy740gW6O2zWWD4GL5m?narsize=4113912",
    },
    "/nix/store/0zc8py7pvw9wbfyym6204ddam722w7rj-gmp-with-cxx-6.3.0": {
        "nar_size": 783432,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/hngmi01i8wgi25a0byrxcn4ysz5j79mw-gcc-15.2.0-lib",
        ],
        "sha256": "f1cd01d4bb336c3fc84e1ae26c08e25cd8e204e2e6bb9d0d4ad8d7ed0de7c579",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIOdoscegCwbbf2ersmg7b_dRVp6hMg651wJyvWqFz9weGBI?narsize=783432",
    },
    "/nix/store/12cm2m4pdfanj5li94hwxpdfzrfdfngj-sqlite-3.51.2": {
        "nar_size": 5862096,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/dbz6pb9g67kpgpl95k8d85kzpxm1c32p-zlib-1.3.2",
        ],
        "sha256": "cd20cefbd4d56004f679ed753f118dc81d41096b61e05274fbfdc9ae83beae5a",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSID8YavL_M3KcdxmSbBVroGQ9rF2GE_KwNXD5cG_wKTtcGA4?narsize=5862096",
    },
    "/nix/store/1396jhi32jf80vrwrnrlyy82wr6d54zn-strace-7.1.tar.xz": {
        "nar_size": 2792752,
        "references": [
        ],
        "sha256": "6b4aff58410d63d158dd9272f9ed914fa2a111e7f19b68a692ab1ac08619a067",
        "url": "https://nixos.snix.store/nar/snix-castore/EicSIJMvmMndGr1GT_g0xXIduCRGPK13sN4jG4rAofAYlkS8GMC5qgE?narsize=2792752",
    },
    "/nix/store/1hrk7xhpm6h98n0lg1qixfrr2kb96zqs-linux-headers-6.18.7": {
        "nar_size": 7328040,
        "references": [
        ],
        "sha256": "c48464648893fff843096b15cb3ed1637ad2a0293c9d56cfec1e5545ae61b3cb",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIA69DNCuGuwEE7jcjl6S7BmQjSLk6n6L-9NFaHpZy9PQGPgQ?narsize=7328040",
    },
    "/nix/store/2hbjnbfhaq4gq6p55xi9qvj6lx7x4g04-gcc-15.2.0-info": {
        "nar_size": 7755136,
        "references": [
        ],
        "sha256": "820f2f8fd282f94ad8f3c9ae037123b1d264e007e3dea46ef42c07dc8627f16a",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSID4zHfmsVYQ5tW-Xr4LUt3Tew3BVFFc52KNqhbiLBsp1GBY?narsize=7755136",
    },
    "/nix/store/32xivk30pdrnhhn2774dha3xphwcgb2v-openssl-3.6.2-doc": {
        "nar_size": 7667576,
        "references": [
        ],
        "sha256": "9ac7ae83f982e4f7ede8a8f7e468117694b941dc080d87908102dfce04dfc3e4",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIIEgK9-3e4qAjMpmONTAR0mg1XLbep4sKGv6zfHuGCn5GKgO?narsize=7667576",
    },
    "/nix/store/35q30dl2xr6874y55dg5ni1dqrvc5650-setup-debug-info-dirs-hook": {
        "nar_size": 592,
        "references": [
        ],
        "sha256": "edd10b640d8fbed2bdcf23b44e3212210b21bbd628368fdf6b1dc0f63adeeb20",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIEy6_kjuTfC-NnFcN-PvSxFSLIXhQ_c1XVxNG1utjCLoGAQ?narsize=592",
    },
    "/nix/store/39lyf5g2iz4jd2r6q4g5whk9vw09zglj-binutils-2.46": {
        "nar_size": 34168344,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/dbz6pb9g67kpgpl95k8d85kzpxm1c32p-zlib-1.3.2",
            "/nix/store/hngmi01i8wgi25a0byrxcn4ysz5j79mw-gcc-15.2.0-lib",
            "/nix/store/y4h9ak6f3z22hvq97jwh90lmc4agx28c-binutils-2.46-lib",
        ],
        "sha256": "ea227240892b088c47a15104230a2af4ce7f064b2cfb64ce9d8fb6c64ef7b874",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIJfli2_3SiBOeYaQlwUu7yREpkSaHQ8Vh3TTpCGaMob7GMYF?narsize=34168344",
    },
    "/nix/store/44fi33grmrbkp2h80a31mqj5lqd3qfwp-bash-interactive-5.3p9-dev": {
        "nar_size": 334704,
        "references": [
            "/nix/store/0641h8qfqaxnwrsw2nzrz6i1wbzyx92l-bash-interactive-5.3p9",
        ],
        "sha256": "d7146496cb66b4db9652520564ed81d011cda0faaea45617954e207672c1f4d8",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIIsVCo-ZlhQ6752ygJCEgVxZXzcxNGmOy0anKHotVOjpGI4B?narsize=334704",
    },
    "/nix/store/4c9lbyb7payh9akmia87v38bi82vdidb-libevent-2.1.12": {
        "nar_size": 882384,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "1057ec7cb5b90256667906b03ad46909397671198e17b51cc87497586c598e2e",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIEhsBU-EqDLFJD9NzeeRvjobsF9DjlAB3QTguvorZ8MfGCI?narsize=882384",
    },
    "/nix/store/4p2xg4f1b5pzabl3hpdnr2sisv74g3nk-ncurses-6.6-dev": {
        "nar_size": 392256,
        "references": [
            "/nix/store/6cblb0wy8kknk5jwj2gzah0jz6ihj3kx-ncurses-6.6-man",
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/mxq1r9w2w2y9lsqb5fkcyb5xbbki1n57-ncurses-6.6",
            "/nix/store/zh1ijdhb6gng1509b1zrilb6xlzx60j6-bash-5.3p9",
        ],
        "sha256": "ed622c2f8dd242e8a701f83343170334416d1324fd147a83d2b2107debf415fc",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIFdtCQ3f2qVf1KHipokNgxPHHYxgcTyEZlee-4a7vzL_GFY?narsize=392256",
    },
    "/nix/store/521dd0054ifhzmjfmpx9mz0hr7wh7sig-glibc-2.42-67-bin": {
        "nar_size": 2890576,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/aasbksznz37vw5pb26wq86209q5cmza8-xgcc-15.2.0-libgcc",
        ],
        "sha256": "1e9d932b2e2ef9adf2202577743ec5a7e046e110b0862881007db69ea730f8a1",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIJUfUxhYkjvsRgCJ9gsZdCsR7--spbeElCAHpchSZf8hGC4?narsize=2890576",
    },
    "/nix/store/5j2akpmlk107gzdqkms35r3nwhkwnibh-bash-interactive-5.3p9-doc": {
        "nar_size": 2222968,
        "references": [
        ],
        "sha256": "927903b26226b6f87bd83801c50690f30ee677b9b3a1a1c1596f5d7f6e2a0d72",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIBodHAE-bATqGY-HT2lUT9BxiOM7TVqH3hZyou0sLalqGBo?narsize=2222968",
    },
    "/nix/store/5ji5924yd02lmva6bmp7k65gfs2696z7-curl-8.20.0": {
        "nar_size": 1221984,
        "references": [
            "/nix/store/009gwlbgzg0ybil10v0q56gpgyvsi3wr-libpsl-0.21.5",
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/d9c9w2y52gffj7zz1b76j0f8fbp5ww4d-libssh2-1.11.1",
            "/nix/store/fsvb5zrsm1n7m5wshm570imspffi7i8f-zstd-1.5.7",
            "/nix/store/j92gvvi4ixkm332fk97mvnq7mary758f-ngtcp2-1.22.1",
            "/nix/store/k6p4kfg37jksiaqkapx0vllh92z7r7id-brotli-1.2.0-lib",
            "/nix/store/kj73fnsp8vd3pr54j1i2acw94nzi63vw-krb5-1.22.2-lib",
            "/nix/store/l0vl4dali2mvbpi30a8da1f71jl85myg-openssl-3.6.2",
            "/nix/store/ql42q1jvff4a97fv669lfnvcq6arz0pa-nghttp3-1.15.0",
            "/nix/store/w73y27sld7x920ffnipw3a8xd1agchdl-nghttp2-1.69.0-lib",
            "/nix/store/zlvydh6q1rv1jza79b21yhi07ic0dkkg-libidn2-2.3.8",
        ],
        "sha256": "8b02977b9842703e96246a7084067a12d05cfc5469f3150624b9b52eb01529cf",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIE1hEhpKARt4gh1CgKgKhMrjnEiJ0KYyRopY9TtW__ctGAo?narsize=1221984",
    },
    "/nix/store/5r95b3z75rc980dws0wp5ylawgzfkj6l-gcc-15.2.0-man": {
        "nar_size": 494632,
        "references": [
        ],
        "sha256": "df03af032989d8fba7ecb5c503a50dfab8aebc054fe3df03e3a412b4eda77fc5",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSICm8_xKE8B8l7_-EBGPY-yLdiEE-9FK7Na6RsaOqwX6lGB4?narsize=494632",
    },
    "/nix/store/61a2wc7hwqg7mqb88g3n1l276zsyrx45-ghc-9.10.3": {
        "nar_size": 1934246688,
        "references": [
            "/nix/store/0zc8py7pvw9wbfyym6204ddam722w7rj-gmp-with-cxx-6.3.0",
            "/nix/store/4p2xg4f1b5pzabl3hpdnr2sisv74g3nk-ncurses-6.6-dev",
            "/nix/store/6srg0xpp58pc1s0qnxx26ny8yqj6yvzx-libffi-3.5.2-dev",
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/a8phd5lf9wrzgz9mrsg4y3rp7si1yakz-elfutils-0.194",
            "/nix/store/chc8cxmnqxgnf4i0y89m292wm6290qsy-libffi-3.5.2",
            "/nix/store/d82g4qdgarx0rxbmgf9k68pr5135y1h6-ghc-9.10.3-doc",
            "/nix/store/g87r0ymgwasv3m4m4n6yplaclnll9zfn-numactl-2.0.18",
            "/nix/store/hngmi01i8wgi25a0byrxcn4ysz5j79mw-gcc-15.2.0-lib",
            "/nix/store/i8s5vsqgsin5m332r62zg26925b4f6qr-gmp-with-cxx-6.3.0-dev",
            "/nix/store/imv1c34sxd6sjrwv0bxxx56j1adwmwrj-elfutils-0.194-dev",
            "/nix/store/mxq1r9w2w2y9lsqb5fkcyb5xbbki1n57-ncurses-6.6",
            "/nix/store/q5wv2ldpcv5w8yb2wmsngsygvlxb73fk-glibc-2.42-67-dev",
            "/nix/store/r9kdpw6c7bhfbr6bcqpd3hgv6zaz3x7z-numactl-2.0.18-dev",
            "/nix/store/sr26flm2nkfa12dkrwj2630kqsfakky4-coreutils-9.11",
            "/nix/store/xcnqqnhw9hb4j5rjgds2yjryi8qki5f3-gcc-wrapper-15.2.0",
            "/nix/store/z4zcd87nx2hrsdayd0vl2mx5ncj3ikd8-binutils-wrapper-2.46",
            "/nix/store/zh1ijdhb6gng1509b1zrilb6xlzx60j6-bash-5.3p9",
        ],
        "sha256": "c0f86c542f0dd843d557b3c5ba5a430f22816a7ee5070b223db53a2faff024c5",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIK4h8-SCrjkrrcjDABfvJAL_jh81VlLoRYjWa8vARJ_UGNJv?narsize=1934246688",
    },
    "/nix/store/67gd1jz8fp4pqb09wws80z9jykx8ykd0-strace-7.1-man": {
        "nar_size": 21544,
        "references": [
        ],
        "sha256": "6919e0e389127345d11d91add8415ecdb2e1b9f7e1f77cc92e04b7cd6b87f61e",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIPNcPxAwvpomdjzbUI3YzopA0PKOJ9CZ-4G3H4I2dtjuGAo?narsize=21544",
    },
    "/nix/store/6cblb0wy8kknk5jwj2gzah0jz6ihj3kx-ncurses-6.6-man": {
        "nar_size": 668400,
        "references": [
        ],
        "sha256": "6d3a5fb66ef99afda8cf80da27af71cf17f82697fb9f91ce6a8c7ca331ddc1e6",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIL7qhz0MwJM1Il0FqZIDafHDMXy7P_-3D7MBPlkRc0zyGNYO?narsize=668400",
    },
    "/nix/store/6srg0xpp58pc1s0qnxx26ny8yqj6yvzx-libffi-3.5.2-dev": {
        "nar_size": 21560,
        "references": [
            "/nix/store/chc8cxmnqxgnf4i0y89m292wm6290qsy-libffi-3.5.2",
        ],
        "sha256": "062e8f259b2e2be97f844de8bef9899e1a31698a06c506372d38143f9eda5494",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIMWRbiJrAFsGK3hXgvzz5Xh3J9nQZh5tjHHR0oDqVY8iGBA?narsize=21560",
    },
    "/nix/store/75bbfamip7akc94cpds1zq3xrjsj048y-gdbm-1.26-lib": {
        "nar_size": 459384,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "0c90544983b18a664c716471ea6f920272d4b82a50c60a131359923a91f94437",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIOf2PIoyKaSmLlvh2YzUYERL_4HYitw1rjTBAwycaRB-GHY?narsize=459384",
    },
    "/nix/store/7nww4d4yl7jzf66qllvyn61xb21vp7ry-gcc-15.2.0-libgcc": {
        "nar_size": 197752,
        "references": [
        ],
        "sha256": "1a427356112d6961148343fdf80f50ab99d97b4d35b28c7297344d95250eefa3",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIG45bgsOOu28sYVtFX013R_uo-USbbGxz8TLuypjog39GAY?narsize=197752",
    },
    "/nix/store/8gyg3xn9i8xdz42yhbl0d3vmmz8phcs0-bzip2-1.0.8": {
        "nar_size": 88952,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "6c3abfa75d55cb36add00e0810568fff58c204af4bccb06a39a979d61add2d54",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIC1tAeBvAvrPxwZPJTFL7qe_cu1DwP8xjhAswGPo7QOUGAw?narsize=88952",
    },
    "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67": {
        "nar_size": 35089528,
        "references": [
            "/nix/store/aasbksznz37vw5pb26wq86209q5cmza8-xgcc-15.2.0-libgcc",
            "/nix/store/zlvydh6q1rv1jza79b21yhi07ic0dkkg-libidn2-2.3.8",
        ],
        "sha256": "bebc77eb57a447f344455d79eedc2e6d4e76d538561c227d69df0eeec5440c3e",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIO3z5lJdbzMvcuqHZhXkS18J9JlH4Ng9qkEcgxUV0fQKGLoQ?narsize=35089528",
    },
    "/nix/store/9nw5g4mx5aghc7rz5viz7ilx3l71qyl8-strace-7.1-debug": {
        "nar_size": 5975352,
        "references": [
            "/nix/store/1396jhi32jf80vrwrnrlyy82wr6d54zn-strace-7.1.tar.xz",
            "/nix/store/afkryhd3wfa29958lc3b1fxjxb60zl6k-strace-7.1",
            "/nix/store/zh1ijdhb6gng1509b1zrilb6xlzx60j6-bash-5.3p9",
        ],
        "sha256": "b11c46e98004cb91371c7e9c881440555ee35fbeb765e441cf954b82012631ed",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSINsHNnDsKi_mtNq_ws7y29qMmb_6uZ_xi5fcwHLqlrwpGCY?narsize=5975352",
    },
    "/nix/store/9zgdw228zjfd4jzr901qzxhfcf43kz91-isl-0.20": {
        "nar_size": 2638360,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/zkw0hl5pzwkmrvkrfvr1q5zlk28nv9v2-gmp-6.3.0",
        ],
        "sha256": "7772d91690a333076c3e58cc118a0003ff6fa973636b5c542895cd9b12719dac",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIAp1Y2VaHcuBD6_Su5S93dD3te2K62wsMwHeBabvJseuGIwB?narsize=2638360",
    },
    "/nix/store/a8phd5lf9wrzgz9mrsg4y3rp7si1yakz-elfutils-0.194": {
        "nar_size": 4223976,
        "references": [
            "/nix/store/5ji5924yd02lmva6bmp7k65gfs2696z7-curl-8.20.0",
            "/nix/store/8gyg3xn9i8xdz42yhbl0d3vmmz8phcs0-bzip2-1.0.8",
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/bbk5ss80g5rgnwgn9b8br4l29km8plh9-xz-5.8.3",
            "/nix/store/dbz6pb9g67kpgpl95k8d85kzpxm1c32p-zlib-1.3.2",
            "/nix/store/dlkag0m5p7b6d6nbhh091hq0s60q6vks-json-c-0.18",
            "/nix/store/fsvb5zrsm1n7m5wshm570imspffi7i8f-zstd-1.5.7",
            "/nix/store/l0vl4dali2mvbpi30a8da1f71jl85myg-openssl-3.6.2",
        ],
        "sha256": "ecf5a5c6da4c58497952709455e8f31de1b6a76107468c15d9c4599c22dd5d3f",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIOQnMeAH06PqeT3RL2WSjSwz-iqD_tGeRhmD4TpNk2CBGF4?narsize=4223976",
    },
    "/nix/store/aagixdk8hcs7p107szv9z17p87mx33nb-expand-response-params": {
        "nar_size": 16808,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "3d6ea5dddbd4f0d8df6a25627b9c43aea63e2fb787026b108687b9feb77a2814",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIObnx6XrPN_PAsPz2Zfn8BWAA_lBHggU4J_76oTSlPyhGAQ?narsize=16808",
    },
    "/nix/store/aasbksznz37vw5pb26wq86209q5cmza8-xgcc-15.2.0-libgcc": {
        "nar_size": 197672,
        "references": [
        ],
        "sha256": "bb680342acc24ea164c86e6fbf8964ff534934de4a5f4f342126331d255abe26",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIJADbdsvSq-hznJdBx32xAlTCtK3XZkEpDQCOsrx06xdGAY?narsize=197672",
    },
    "/nix/store/afkryhd3wfa29958lc3b1fxjxb60zl6k-strace-7.1": {
        "nar_size": 3543088,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/a8phd5lf9wrzgz9mrsg4y3rp7si1yakz-elfutils-0.194",
            "/nix/store/zh1ijdhb6gng1509b1zrilb6xlzx60j6-bash-5.3p9",
        ],
        "sha256": "71e215a5f10e9f026552f7bd6af70a56c3f982a90db29d6082948b5bb90cd8da",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIPVcTx7HULLqRZlgllUnqMULfwyfjzVfPglrzmS6hDwtGAY?narsize=3543088",
    },
    "/nix/store/b67fr4nba948zxxpmdsnzqr06l9fnnag-bash-interactive-5.3p9-man": {
        "nar_size": 110024,
        "references": [
        ],
        "sha256": "3cc4f7f5d7c94a8ba139edb6bc8e72f60ac57b5a4e085fbb439923dea1e2668a",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIEBFv9_STv1LlG0eLAeue3PPp-bSXjudd4yVbwneaMXoGAo?narsize=110024",
    },
    "/nix/store/bbk5ss80g5rgnwgn9b8br4l29km8plh9-xz-5.8.3": {
        "nar_size": 857952,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "19e096880840a7e748a5a60fc52da532de85a68c0a31d0e85038fb359b8fa1c0",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSICmgBa3TrOm2lJHbOLpjZ3pqS-i3fTvld95J37b3TQ3eGKQB?narsize=857952",
    },
    "/nix/store/c0i98bjjwf0lcmrh97123qayrzchxz3d-libmpc-1.4.0": {
        "nar_size": 308776,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/wzigz21rnv9nj8g7r8ai8ldm84zqnhda-mpfr-4.2.2",
            "/nix/store/zkw0hl5pzwkmrvkrfvr1q5zlk28nv9v2-gmp-6.3.0",
        ],
        "sha256": "17c8cedecd99fa0d8a3c8c5bae82eb0243970ad8c33430d61a833e5377fbe9f1",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIG_ZSnR3TdzY1J-6Tzt2a8706mdV1gh8RcfxzX4NgVqqGBg?narsize=308776",
    },
    "/nix/store/c2d7chn37a4q79xby5k12kcdqa905vnl-openssl-3.6.2.tar.gz": {
        "nar_size": 54913672,
        "references": [
        ],
        "sha256": "80ce2e43eb0457bb02c64cd3fa70c70b77682532492372c36e3c80aa841ec3cd",
        "url": "https://nixos.snix.store/nar/snix-castore/EicSIBF656ADloT5JFz9wxIH4AMcihR5cIG0uty9kNtzef77GJTUlxo?narsize=54913672",
    },
    "/nix/store/c985nba7m9vjl11i39wwhdpxnkxhlz1f-keyutils-1.6.3-lib": {
        "nar_size": 42848,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "b0ba1c0b5aa37f0beafa50d62df10c78feccc734d62874f1fce9a76be4e6733a",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIA4Pd0s-_QqTmTq71CC8_4wAX6uXc-9_BJzVmVAFndb7GAo?narsize=42848",
    },
    "/nix/store/chc8cxmnqxgnf4i0y89m292wm6290qsy-libffi-3.5.2": {
        "nar_size": 73816,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "8ec62c9599342bd079378a751184646cdf9b5fefb05839197919aad21d9391ac",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSILvIFe4RGHCAd6ZJ1OFWV2BY62XePwVQi_kOWOvezuGYGAw?narsize=73816",
    },
    "/nix/store/clvbx203wyqkdnqc5ngyhjlhcqn5s9x9-openssl-3.6.2-bin": {
        "nar_size": 1323736,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/l0vl4dali2mvbpi30a8da1f71jl85myg-openssl-3.6.2",
        ],
        "sha256": "fcc32dbed18685d8a37222d35cfbb7369a51d55e2b0d1179f45d7bf76fe3111f",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSINPEDoVms1SMZvFrqd9IIMkoTs-aBDVgcatm4CjFzjoyGAY?narsize=1323736",
    },
    "/nix/store/d3y9krrxjz9xyrwfr2f71d1yk6ck95yx-p11-kit-0.26.2": {
        "nar_size": 5987016,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/chc8cxmnqxgnf4i0y89m292wm6290qsy-libffi-3.5.2",
            "/nix/store/qa77jydj4h1n2lj4gzshrmkvinkaz3y1-libtasn1-4.21.0",
        ],
        "sha256": "647bd4854669ed38a1bfb6fc212ae2d95feb7a4cce195861cf95554f1556847b",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIGKJRXgIV18rg04T8cg3NK8TL5pg_MjkZJguo-9D__DMGNwD?narsize=5987016",
    },
    "/nix/store/d56bcbhz02g29c3lh770db2y0g7f5zg0-Python-3.13.13.tar.xz": {
        "nar_size": 22957728,
        "references": [
        ],
        "sha256": "8312403b92ae6d447af0211dcd1ee9432e36057494cf4ea8ed7786534673acb4",
        "url": "https://nixos.snix.store/nar/snix-castore/EicSILXMLjkzvj5i-A_RfSf8pwqxQjpteaVGBZKv6EIesFzYGKyc-Qo?narsize=22957728",
    },
    "/nix/store/d82g4qdgarx0rxbmgf9k68pr5135y1h6-ghc-9.10.3-doc": {
        "nar_size": 788224512,
        "references": [
            "/nix/store/0641h8qfqaxnwrsw2nzrz6i1wbzyx92l-bash-interactive-5.3p9",
        ],
        "sha256": "433c3ccd92327ac2dc9400e5c16825214a0ac542c03da420274ae951114b8b32",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIKm1p0Rai2DGCV-gzXyVINTKgyXv5KHjNXAVdnrWnfrQGLZc?narsize=788224512",
    },
    "/nix/store/d9c9w2y52gffj7zz1b76j0f8fbp5ww4d-libssh2-1.11.1": {
        "nar_size": 334416,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/dbz6pb9g67kpgpl95k8d85kzpxm1c32p-zlib-1.3.2",
            "/nix/store/l0vl4dali2mvbpi30a8da1f71jl85myg-openssl-3.6.2",
        ],
        "sha256": "fca7c90fa3e13ffd810a49d17840a1b0092641526ef0309458349c461ca69dd7",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIF1mnwmd2xfPF6_MtRRoS_9biUF7JDxiYIOn0Ai4xtbDGAo?narsize=334416",
    },
    "/nix/store/dbz6pb9g67kpgpl95k8d85kzpxm1c32p-zlib-1.3.2": {
        "nar_size": 132608,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "7d3bbdecf481e696153d088b375e795671624d03c1838e8ec7dd2272d889c0eb",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIN1xImTrRAh72HlJxGpQXlh3BfceQajLhPfdQyb7RABGGBA?narsize=132608",
    },
    "/nix/store/dlkag0m5p7b6d6nbhh091hq0s60q6vks-json-c-0.18": {
        "nar_size": 250712,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "272f1032b34a248663956fd600805e179e7a2e970fb8e044bf8390336705ebda",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSINxefdAo2ngtagD7E3jZnwEsc4hEZHZDlQZli2NnItSlGAo?narsize=250712",
    },
    "/nix/store/dxqah042znlglapf07vha4qannacibf2-gcc-wrapper-15.2.0-man": {
        "nar_size": 176,
        "references": [
            "/nix/store/5r95b3z75rc980dws0wp5ylawgzfkj6l-gcc-15.2.0-man",
        ],
        "sha256": "80fb60bbf05a1bb57328b4c6afd81ecc46218139cd199b3a8770b2176165ad57",
        "url": "https://nixos.snix.store/nar/snix-castore/GjwSOi9uaXgvc3RvcmUvNXI5NWIzejc1cmM5ODBkd3Mwd3A1eWxhd2d6ZmtqNmwtZ2NjLTE1LjIuMC1tYW4?narsize=176",
    },
    "/nix/store/fr3qqvg4iylba6hpf53pr9k27ddv2826-libarchive-3.8.7-lib": {
        "nar_size": 972616,
        "references": [
            "/nix/store/8gyg3xn9i8xdz42yhbl0d3vmmz8phcs0-bzip2-1.0.8",
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/bbk5ss80g5rgnwgn9b8br4l29km8plh9-xz-5.8.3",
            "/nix/store/dbz6pb9g67kpgpl95k8d85kzpxm1c32p-zlib-1.3.2",
            "/nix/store/fsvb5zrsm1n7m5wshm570imspffi7i8f-zstd-1.5.7",
            "/nix/store/hm2ixz0mgyx22sxzihs8ix1rsj2g36y6-libxml2-2.15.3",
            "/nix/store/l0vl4dali2mvbpi30a8da1f71jl85myg-openssl-3.6.2",
            "/nix/store/x0zgiss9hdzcsll3cswgfa937aqs12rq-acl-2.3.2",
        ],
        "sha256": "b08f44d1a4df6ddd79fb296083c0f36c113363e064e8793ec00e2ae0e374c022",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIIfWKhftlzRHEyks4PQpMbDBzy_LWLvEJcapMEjpdFwCGAo?narsize=972616",
    },
    "/nix/store/fsvb5zrsm1n7m5wshm570imspffi7i8f-zstd-1.5.7": {
        "nar_size": 1202224,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/hngmi01i8wgi25a0byrxcn4ysz5j79mw-gcc-15.2.0-lib",
        ],
        "sha256": "be3fc8c816facd7f09bdb10ce0244a080b988f8e9aa63419780ce970e8dc391d",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIDX1708z9N-zGCWP3KA5n7u-Rn71bc_ub-4t44pyNrTOGBQ?narsize=1202224",
    },
    "/nix/store/g2pg1an3v5pm2fmwg1g7dw77ddpqirg7-python3-3.13.13-debug": {
        "nar_size": 26009416,
        "references": [
            "/nix/store/d56bcbhz02g29c3lh770db2y0g7f5zg0-Python-3.13.13.tar.xz",
            "/nix/store/l9k0anq0z7zz81zcwy035jfwap9ga6rl-python3-3.13.13",
            "/nix/store/xakkd7mhg6dindq35ji8smr4j9ypwpn7-mailcap-2.1.54",
            "/nix/store/zh1ijdhb6gng1509b1zrilb6xlzx60j6-bash-5.3p9",
        ],
        "sha256": "8e4edf15eed16cdbb67c4ab8abf5ae4fe56ba0742a72a81a744d48dca8900196",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIEch95AU62DJfj0GPdIPm7o4CgJq1gObBGujxWxEZb6FGMoH?narsize=26009416",
    },
    "/nix/store/g87r0ymgwasv3m4m4n6yplaclnll9zfn-numactl-2.0.18": {
        "nar_size": 276408,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/hngmi01i8wgi25a0byrxcn4ysz5j79mw-gcc-15.2.0-lib",
        ],
        "sha256": "2973895c30954dfa7fb99b439fd7027d58b424b1596182f754c372c99dfb3bb4",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSILCMh_zOrv7aU4TBZdUdu3wNm0yAcybzF4CjRzA2EFhoGBg?narsize=276408",
    },
    "/nix/store/ga3b95jkyvknam1nxl25r95nyk87ix25-tzdata-2026b": {
        "nar_size": 2148320,
        "references": [
        ],
        "sha256": "988c98902b0b7e0414b5759d7144559f6d8ea2da1ba52d960860a9004b0de4e0",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSII-xmdZ0Ve5dHkzxzDq0XqFxWHUUx43fG84F__gUVcfiGMQU?narsize=2148320",
    },
    "/nix/store/hm2ixz0mgyx22sxzihs8ix1rsj2g36y6-libxml2-2.15.3": {
        "nar_size": 1460416,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "b991baa519640c5932e93a50f8528481733cbbe06895126dfdaa72dbe35d1760",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIHLNcYpXj9x-gYXDKquXmDZo2nJKAUDzmIMjstFWgyLMGAo?narsize=1460416",
    },
    "/nix/store/hngmi01i8wgi25a0byrxcn4ysz5j79mw-gcc-15.2.0-lib": {
        "nar_size": 10313656,
        "references": [
            "/nix/store/7nww4d4yl7jzf66qllvyn61xb21vp7ry-gcc-15.2.0-libgcc",
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "4c790e12bef90176bce1311ab62bd5666a5d7cfd573953f32819d388d7636c69",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSII-5mmzJRN9kLajb-YSdPhYf3ApWJBFpjWG36jI3qD1EGFw?narsize=10313656",
    },
    "/nix/store/i0jqva96qfgc76g8w7jbyiv6h3si07b9-openssl-3.6.2-dev": {
        "nar_size": 2043112,
        "references": [
            "/nix/store/clvbx203wyqkdnqc5ngyhjlhcqn5s9x9-openssl-3.6.2-bin",
            "/nix/store/l0vl4dali2mvbpi30a8da1f71jl85myg-openssl-3.6.2",
        ],
        "sha256": "2989011b6cea84916851a7dab8bb5cdcdb0a9a1699c398006df951078323fc23",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIHeGAtXRB7kOuksrMCvPnyXFlTX5GzSUJXkd6zDq8vXuGK4C?narsize=2043112",
    },
    "/nix/store/i8s5vsqgsin5m332r62zg26925b4f6qr-gmp-with-cxx-6.3.0-dev": {
        "nar_size": 216392,
        "references": [
            "/nix/store/0zc8py7pvw9wbfyym6204ddam722w7rj-gmp-with-cxx-6.3.0",
        ],
        "sha256": "0133f4498b26b923f070509796861eec814765f09185402b988d9bc24d868b2e",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIKSky0LPlUTTVMTb1fOowiNW6z-L7KAKhfpQEdGWII-_GBI?narsize=216392",
    },
    "/nix/store/im7mcigg1x2bq9rg7z3h3i26pjmss0c7-readline-8.3p3": {
        "nar_size": 506392,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/mxq1r9w2w2y9lsqb5fkcyb5xbbki1n57-ncurses-6.6",
        ],
        "sha256": "e8fb017cedd68abde253d0eacdb4068425355355893f287ed16006070d25c3dd",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIAB0NA1X43OEWZbO_0qMk0T6EeCoQZYc05pnJxANY1BCGBA?narsize=506392",
    },
    "/nix/store/imv1c34sxd6sjrwv0bxxx56j1adwmwrj-elfutils-0.194-dev": {
        "nar_size": 246152,
        "references": [
            "/nix/store/35q30dl2xr6874y55dg5ni1dqrvc5650-setup-debug-info-dirs-hook",
            "/nix/store/a8phd5lf9wrzgz9mrsg4y3rp7si1yakz-elfutils-0.194",
            "/nix/store/j81457fd9dyd8ck5577h6jp03psd5f7d-elfutils-0.194-bin",
        ],
        "sha256": "c665cbb6e0c59a2723bf40efc459e445bd48d8594ba8e7095825228471b781a4",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIBw98B00hX9TvuOFaiqU5uB-KFFOXftU-BImVZiWx5poGC4?narsize=246152",
    },
    "/nix/store/ipz4lbivx3q7gr79130d6g5ix35vibnw-libunistring-1.4.2": {
        "nar_size": 2078944,
        "references": [
        ],
        "sha256": "d7d9f55c19ceb85dd9805a89a627aebaf2ed563ca907b7f637b0591fb493a152",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIB-YHHcT3oSRPZkUyRvtuW_7AnQ1SBo9Cg7nHwehFFdfGAo?narsize=2078944",
    },
    "/nix/store/j81457fd9dyd8ck5577h6jp03psd5f7d-elfutils-0.194-bin": {
        "nar_size": 3715760,
        "references": [
            "/nix/store/12cm2m4pdfanj5li94hwxpdfzrfdfngj-sqlite-3.51.2",
            "/nix/store/5ji5924yd02lmva6bmp7k65gfs2696z7-curl-8.20.0",
            "/nix/store/8gyg3xn9i8xdz42yhbl0d3vmmz8phcs0-bzip2-1.0.8",
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/a8phd5lf9wrzgz9mrsg4y3rp7si1yakz-elfutils-0.194",
            "/nix/store/bbk5ss80g5rgnwgn9b8br4l29km8plh9-xz-5.8.3",
            "/nix/store/dlkag0m5p7b6d6nbhh091hq0s60q6vks-json-c-0.18",
            "/nix/store/fr3qqvg4iylba6hpf53pr9k27ddv2826-libarchive-3.8.7-lib",
            "/nix/store/hngmi01i8wgi25a0byrxcn4ysz5j79mw-gcc-15.2.0-lib",
            "/nix/store/ylirzjzp6fxm8xdp8547kbbshbwydxs2-libmicrohttpd-1.0.2",
            "/nix/store/zh1ijdhb6gng1509b1zrilb6xlzx60j6-bash-5.3p9",
        ],
        "sha256": "b21ed2e57d3c17f3d4bc49ac80c9675d7f6667a7cdf9245eb5bcd8404dbfb24e",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIM6gWeO6aenqlL5fsEz5wCh2pXztEuBKcyXEVONyyS1RGCo?narsize=3715760",
    },
    "/nix/store/j92gvvi4ixkm332fk97mvnq7mary758f-ngtcp2-1.22.1": {
        "nar_size": 495896,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/l0vl4dali2mvbpi30a8da1f71jl85myg-openssl-3.6.2",
        ],
        "sha256": "a8a59fd394a02649c56f6d554351a2e798e0bd001c2f1ab70f55ab192bee5207",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSICYKQ2nG-8TWRpM56g5AIUgYR0sfcQQAvl95JvKql_KyGA4?narsize=495896",
    },
    "/nix/store/k6p4kfg37jksiaqkapx0vllh92z7r7id-brotli-1.2.0-lib": {
        "nar_size": 984976,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "cf18c47f661917cf36d0a8421630a1eff6d59cf5aebf85a6b5dbf65eb165b445",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIPnoUdMqytGY_pZ4s5MTnXlWRkDjA2BAWe2R6VL-5XxBGBQ?narsize=984976",
    },
    "/nix/store/k7kxg101ikkm0cyf8jcqhg948vy542af-perl-5.42.0": {
        "nar_size": 57724584,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/dbz6pb9g67kpgpl95k8d85kzpxm1c32p-zlib-1.3.2",
            "/nix/store/mlcv28rh7faq6iqmm9vkny11hbbicgir-libxcrypt-4.5.2",
            "/nix/store/sr26flm2nkfa12dkrwj2630kqsfakky4-coreutils-9.11",
        ],
        "sha256": "25f91d462137e5b0f4f812be897eede587899c8d15a7568802b3774055e0d9fa",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSILrGO13CcNr3pRTmN4gaICKz8hW6fqk1aJLD9i7isR7YGPIi?narsize=57724584",
    },
    "/nix/store/kh4j2kji7i38viz4h0cf6kbv9fnvhnkg-unbound-1.25.1-lib": {
        "nar_size": 1182064,
        "references": [
            "/nix/store/0zc8py7pvw9wbfyym6204ddam722w7rj-gmp-with-cxx-6.3.0",
            "/nix/store/4c9lbyb7payh9akmia87v38bi82vdidb-libevent-2.1.12",
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/v9c75y1hd6yzlgiwvxriigylqgznq3rg-nettle-3.10.2",
        ],
        "sha256": "777a18a3303a42c17db1fc0a65f6654d69e8d707158434d53a07c5a19608d0b2",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIERDFIZsFfJOBJwWObooEyISyQu5b8Xw_CMag1TrqcJNGAo?narsize=1182064",
    },
    "/nix/store/kj73fnsp8vd3pr54j1i2acw94nzi63vw-krb5-1.22.2-lib": {
        "nar_size": 2879776,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/c985nba7m9vjl11i39wwhdpxnkxhlz1f-keyutils-1.6.3-lib",
            "/nix/store/l0vl4dali2mvbpi30a8da1f71jl85myg-openssl-3.6.2",
        ],
        "sha256": "712285518788c2bfd146f386a2586ce5e30fbdf7cd144cee8f1da2007d21b602",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIGkwvfcaIq9XdbhDzS4Bs505hLJNAKpwfH4WQyiMmuXJGHo?narsize=2879776",
    },
    "/nix/store/kwm524zjlnnq4yfhhmb5r14f2wxf8a2j-bash-5.3.tar.gz": {
        "nar_size": 11355968,
        "references": [
        ],
        "sha256": "91c5d54f6842882b67fcbfca123fc48a1186f6d1fe2a7bccbd048e0888d0da2a",
        "url": "https://nixos.snix.store/nar/snix-castore/EicSIFvzrGwY89w_4-BJoeEOpa5cWznawjVs15ZzD0myc_0PGM6NtQU?narsize=11355968",
    },
    "/nix/store/l0vl4dali2mvbpi30a8da1f71jl85myg-openssl-3.6.2": {
        "nar_size": 9303968,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "c8d7d663b6e9319a464f3392a00466b605c6bf8a8f9abb17be3e7178ea1142c6",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIBZfjOCEpmJoXjqNXjTIbgSYTpu8PuoExtrY61cFQGS1GCQ?narsize=9303968",
    },
    "/nix/store/l76krav3w28kmd2b00lb687i1ykswvp0-bash-interactive-5.3p9-debug": {
        "nar_size": 3585496,
        "references": [
            "/nix/store/0641h8qfqaxnwrsw2nzrz6i1wbzyx92l-bash-interactive-5.3p9",
            "/nix/store/kwm524zjlnnq4yfhhmb5r14f2wxf8a2j-bash-5.3.tar.gz",
            "/nix/store/zh1ijdhb6gng1509b1zrilb6xlzx60j6-bash-5.3p9",
        ],
        "sha256": "64bb7fe06920e1d77a5c71730a837cd17187c27b1d92d425edeaf22d3c8b34ef",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSINYOImlDeAmqPs5fBHEpCK62VWLLjlvYgD00B2WW-XLmGJ4E?narsize=3585496",
    },
    "/nix/store/l9k0anq0z7zz81zcwy035jfwap9ga6rl-python3-3.13.13": {
        "nar_size": 133021280,
        "references": [
            "/nix/store/12cm2m4pdfanj5li94hwxpdfzrfdfngj-sqlite-3.51.2",
            "/nix/store/75bbfamip7akc94cpds1zq3xrjsj048y-gdbm-1.26-lib",
            "/nix/store/8gyg3xn9i8xdz42yhbl0d3vmmz8phcs0-bzip2-1.0.8",
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/bbk5ss80g5rgnwgn9b8br4l29km8plh9-xz-5.8.3",
            "/nix/store/chc8cxmnqxgnf4i0y89m292wm6290qsy-libffi-3.5.2",
            "/nix/store/dbz6pb9g67kpgpl95k8d85kzpxm1c32p-zlib-1.3.2",
            "/nix/store/ga3b95jkyvknam1nxl25r95nyk87ix25-tzdata-2026b",
            "/nix/store/hngmi01i8wgi25a0byrxcn4ysz5j79mw-gcc-15.2.0-lib",
            "/nix/store/im7mcigg1x2bq9rg7z3h3i26pjmss0c7-readline-8.3p3",
            "/nix/store/l0vl4dali2mvbpi30a8da1f71jl85myg-openssl-3.6.2",
            "/nix/store/lawdl6fwyj55dign3dasn96cy1asgags-expat-2.8.1",
            "/nix/store/mxq1r9w2w2y9lsqb5fkcyb5xbbki1n57-ncurses-6.6",
            "/nix/store/nvzf6a62pyd9fsddawhl2dwhm7sjcby4-util-linux-minimal-2.42-lib",
            "/nix/store/xakkd7mhg6dindq35ji8smr4j9ypwpn7-mailcap-2.1.54",
            "/nix/store/xnlpfhi3m3in4b1h8h905hpv97gc8b07-mpdecimal-4.0.1",
            "/nix/store/zh1ijdhb6gng1509b1zrilb6xlzx60j6-bash-5.3p9",
        ],
        "sha256": "73d848d14f15f21c82b7e377a5977b4bcb31efcfef1820a6b6986d18c1132367",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSILzFHnjgyowURnUgPv2_JpbbGO9j0URncAl1LaeqtuiNGM43?narsize=133021280",
    },
    "/nix/store/lawdl6fwyj55dign3dasn96cy1asgags-expat-2.8.1": {
        "nar_size": 314696,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "80a4ed0fd3c2e63094317e4e922abf67feae699a61743f9166e4b08b30b4e5f2",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIKjmWFJQ1xvYyYwGVDFl4xzPlq640tCWBHqrtlajhWxoGBQ?narsize=314696",
    },
    "/nix/store/mbbchsqa44gcx16skf6v6c6bqiayamc9-dns-root-data-2025-04-14": {
        "nar_size": 4968,
        "references": [
        ],
        "sha256": "c1318ab3829857a085d5669e98086d473c9e5ec85cb8efe4c8fa508837476feb",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIEhrxuhWoidDHZuE_rPvSn7xS299crpeT1JfLppBUvdXGAY?narsize=4968",
    },
    "/nix/store/mlcv28rh7faq6iqmm9vkny11hbbicgir-libxcrypt-4.5.2": {
        "nar_size": 144384,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "6bdf1c3a5be0fa0949c070b81e6d50ab5c7df089d0247d1e8787b1f91c933c4b",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIC0tRPtFRj19P8P-_qvRRwj2rIu3gdZQauG8ktoXXf5RGBQ?narsize=144384",
    },
    "/nix/store/mxq1r9w2w2y9lsqb5fkcyb5xbbki1n57-ncurses-6.6": {
        "nar_size": 3870560,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "24c339da69ad407a4a6a414c0efe19f2c15152e6094f0468a2e0854fe3dd02c1",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIL8V7A_17hySfxig3-6TmjfUgIyaPseiXYhNpXADh1hCGMwu?narsize=3870560",
    },
    "/nix/store/nm7p8wxflggcwxfzayhysq4z6a1wg373-hello-2.12.3": {
        "nar_size": 279624,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "6735e3d980e2c2478116f34df9c4e6211c929b2dd980ade8b74e2ecfc6796f38",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSILd0unJhoKVQ9739Cz4rWe26E5M4aqpDXVP0tRKC-bhkGKYC?narsize=279624",
    },
    "/nix/store/nvzf6a62pyd9fsddawhl2dwhm7sjcby4-util-linux-minimal-2.42-lib": {
        "nar_size": 2100616,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "7cd6596984f46dd6a9d5a4a3ea07d30dfa1f9e01c5e905a03df72e9253a73aff",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIE5JF26r5fm-6_0u6ILL9zSXUZtdO9ad49OuEKupotD-GCo?narsize=2100616",
    },
    "/nix/store/p59cz49l5faa67c72wxdql3jfj9gy2fn-coreutils-9.11.tar.xz": {
        "nar_size": 6562536,
        "references": [
        ],
        "sha256": "40a12e037c5ce1803e9058630ecdc4ab6a1298639b67cd0a54776e7d7e76f7b8",
        "url": "https://nixos.snix.store/nar/snix-castore/EicSIG8yQ6TfxJjC9eyMVQ1Kg6f5Tq16LHQ8obMUwbdNqBJdGPTEkAM?narsize=6562536",
    },
    "/nix/store/pcar1vqvmn2y42lplzca392yx605kk31-gcc-wrapper-15.2.0-info": {
        "nar_size": 176,
        "references": [
            "/nix/store/2hbjnbfhaq4gq6p55xi9qvj6lx7x4g04-gcc-15.2.0-info",
        ],
        "sha256": "6b89b7183963077b7840cbd9c5b2f2b069d1bc5074fea7f528d698407f5b02f3",
        "url": "https://nixos.snix.store/nar/snix-castore/Gj0SOy9uaXgvc3RvcmUvMmhiam5iZmhhcTRncTZwNTV4aTlxdmo2bHg3eDRnMDQtZ2NjLTE1LjIuMC1pbmZv?narsize=176",
    },
    "/nix/store/pspjmjsphdkjsi20gpxh2p1aq6p73n1c-bash-interactive-5.3p9-info": {
        "nar_size": 640520,
        "references": [
        ],
        "sha256": "9d4271cb9cd8ef6994afebb5474ff6753279defba4dbe55683e91a9de04beb98",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIPNrWTfbuodNkTEq8kAbwW7oJJEdHkqLLMjKxHZb0XtgGAY?narsize=640520",
    },
    "/nix/store/pzpmwj3agpmlkjfq0g62r2zxa7qysdya-bash-static-5.3": {
        "nar_size": 10111128,
        "references": [
        ],
        "sha256": "6b98866bb64d03f259e3457e4a02c64094e9aae32339ce301b5ce6308ea2eb9c",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIHRROFn36AQXne6bvyqaaqZBvXt_WgoqOyhAnDkjqFfoGKQC?narsize=10111128",
    },
    "/nix/store/q5wv2ldpcv5w8yb2wmsngsygvlxb73fk-glibc-2.42-67-dev": {
        "nar_size": 2445264,
        "references": [
            "/nix/store/1hrk7xhpm6h98n0lg1qixfrr2kb96zqs-linux-headers-6.18.7",
            "/nix/store/521dd0054ifhzmjfmpx9mz0hr7wh7sig-glibc-2.42-67-bin",
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "4ced81e2c8db284d2680da055ee7e94e303094ef0d90cb1a89dcd303ee1a1886",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIJL3moZmaWygPqGat6fRSpHlDIbAN6mIZVLxGGTBSA17GJII?narsize=2445264",
    },
    "/nix/store/qa77jydj4h1n2lj4gzshrmkvinkaz3y1-libtasn1-4.21.0": {
        "nar_size": 98096,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "ab74d90dfa1b6efba534e6cda62e139cd7d64190a46abb77d41346071cd5375d",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIBH4ylox_1XJD_nrSsCeVpm_hopSPeJgRjor2DHY-iR_GAo?narsize=98096",
    },
    "/nix/store/qjxwvydl5f07l8zgg6p2pyypll8ybc9n-publicsuffix-list-0-unstable-2026-05-13": {
        "nar_size": 337752,
        "references": [
        ],
        "sha256": "4686269392713ce900ad5f35e730e44452b1ab1241c8af6a63b050cad471e95e",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIERGM_-UgDRC-TrLEfy1YZcbnbhSA9eaZw2Lcth_R3SSGAg?narsize=337752",
    },
    "/nix/store/ql42q1jvff4a97fv669lfnvcq6arz0pa-nghttp3-1.15.0": {
        "nar_size": 233128,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "01e60e076c2df7bac0db0857a454f04c28b1b36378991675a1fd634105c3a8d2",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIFTa5Bl7A3qEhDIn7l8ZeZZKB8fxvv8jZ5y7hJU9OktEGAg?narsize=233128",
    },
    "/nix/store/r9kdpw6c7bhfbr6bcqpd3hgv6zaz3x7z-numactl-2.0.18-dev": {
        "nar_size": 19656,
        "references": [
            "/nix/store/g87r0ymgwasv3m4m4n6yplaclnll9zfn-numactl-2.0.18",
        ],
        "sha256": "5c243c4291eb70ac6015fb63c153194c2a5219a13a311a48be80b734a1bb68c3",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIO6FOMgWHhDV7DlZP4piMy-WoRlMuUJOV1FXHwa9C9_NGBI?narsize=19656",
    },
    "/nix/store/rfabfsmwq02sn94mb3qg9jwvxbqfwmsr-gmp-with-cxx-6.3.0": {
        "nar_size": 783432,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/hngmi01i8wgi25a0byrxcn4ysz5j79mw-gcc-15.2.0-lib",
        ],
        "sha256": "651d702d6f8107e27e05d4bb16d8a01a3ea411491238e56982b3e7aefbec79d1",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIK-iqf21gh9zsci6YT3_hJZe_sknPwppjzijdDz6qptnGBI?narsize=783432",
    },
    "/nix/store/sq0nrnfwhkc5ljvklnrk5ps4358g4nbj-gcc-15.2.0": {
        "nar_size": 276918792,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/9zgdw228zjfd4jzr901qzxhfcf43kz91-isl-0.20",
            "/nix/store/c0i98bjjwf0lcmrh97123qayrzchxz3d-libmpc-1.4.0",
            "/nix/store/dbz6pb9g67kpgpl95k8d85kzpxm1c32p-zlib-1.3.2",
            "/nix/store/hngmi01i8wgi25a0byrxcn4ysz5j79mw-gcc-15.2.0-lib",
            "/nix/store/q5wv2ldpcv5w8yb2wmsngsygvlxb73fk-glibc-2.42-67-dev",
            "/nix/store/wzigz21rnv9nj8g7r8ai8ldm84zqnhda-mpfr-4.2.2",
            "/nix/store/zkw0hl5pzwkmrvkrfvr1q5zlk28nv9v2-gmp-6.3.0",
        ],
        "sha256": "c91f720906fe91712f0917bd8088c1a64859e4ebf795fc3a133f19384a86b82f",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIIA-60cZSF4dXj8kMTmijCh5JUssr2CKF880uhEmQoATGOgb?narsize=276918792",
    },
    "/nix/store/sr26flm2nkfa12dkrwj2630kqsfakky4-coreutils-9.11": {
        "nar_size": 1806736,
        "references": [
            "/nix/store/08nfpyc4qhzdkc37nznvfpbybihyr063-attr-2.5.2",
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/rfabfsmwq02sn94mb3qg9jwvxbqfwmsr-gmp-with-cxx-6.3.0",
            "/nix/store/x0zgiss9hdzcsll3cswgfa937aqs12rq-acl-2.3.2",
        ],
        "sha256": "1c5f717d2bfc0c3d7a057a2f34272a3debb4adb66652092b078b72b11bdca8c9",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIOdFpJG0Y26nDqzE3KL6R2ZrTKEAGrvRB1Fyu8eswvLOGN4B?narsize=1806736",
    },
    "/nix/store/v9c75y1hd6yzlgiwvxriigylqgznq3rg-nettle-3.10.2": {
        "nar_size": 740848,
        "references": [
            "/nix/store/0zc8py7pvw9wbfyym6204ddam722w7rj-gmp-with-cxx-6.3.0",
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "d779680355355886c80b1c832f348cc5750ef325d8b61a21b1d8b5932d47826e",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIEyI7CKhezBTrvTOgQriocc4zuxXXEiC7Ot88N217DStGA4?narsize=740848",
    },
    "/nix/store/w73y27sld7x920ffnipw3a8xd1agchdl-nghttp2-1.69.0-lib": {
        "nar_size": 230728,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "d8ff4e4ce19e117246c35611993562b2a44300169d788d0c6433ccc80b873fd0",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIOYvrmQwMLCiioERvHhzA2WxGuG3b7xHT4gme05fcZ2TGAo?narsize=230728",
    },
    "/nix/store/w8xlvapzxcz23ba312q119p57bnc7200-gnugrep-3.12": {
        "nar_size": 954768,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/x2zjc47pkhcwxr4iyv5xj3hdqfzfnyd9-pcre2-10.46",
        ],
        "sha256": "5bf9b8b7a4ab2cdee8aa640d0ec879cb1f74ec1fe6a733598af3c792af84da30",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSILVWtkRcwGInwP4EHAJ5KyhH1fxHNeRotWj586S5sxzaGKAC?narsize=954768",
    },
    "/nix/store/wifadx5v4ps5nvf23cr22lswn3q70s6f-coreutils-9.11-debug": {
        "nar_size": 5824968,
        "references": [
            "/nix/store/p59cz49l5faa67c72wxdql3jfj9gy2fn-coreutils-9.11.tar.xz",
            "/nix/store/pzpmwj3agpmlkjfq0g62r2zxa7qysdya-bash-static-5.3",
            "/nix/store/sr26flm2nkfa12dkrwj2630kqsfakky4-coreutils-9.11",
        ],
        "sha256": "008290716be7466e515d4ce1cab214f2d2b0d347955e18fc8e120f9141f5913b",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIFCIutMy9pIJ78gnZ-aJVKIukW3QBuXp-3Ga-VqKCuLnGNYC?narsize=5824968",
    },
    "/nix/store/wzigz21rnv9nj8g7r8ai8ldm84zqnhda-mpfr-4.2.2": {
        "nar_size": 822600,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/zkw0hl5pzwkmrvkrfvr1q5zlk28nv9v2-gmp-6.3.0",
        ],
        "sha256": "588981d77dd96e4895b742b9131698aac97dcd195873a326623d587b16593bb3",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIKRdQFzMRpNrJPv9X7R5Ns0mariqSLeFBL-tOXOPj5VdGAo?narsize=822600",
    },
    "/nix/store/x0zgiss9hdzcsll3cswgfa937aqs12rq-acl-2.3.2": {
        "nar_size": 128224,
        "references": [
            "/nix/store/08nfpyc4qhzdkc37nznvfpbybihyr063-attr-2.5.2",
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "620c73ef1f54bf0690493fbdd36621c7f00edc0f01f48084387ff9083539e695",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIN7c4mSx9rD7CAGP1toHk0gb_bs-uKOvfahPSrsYE545GEQ?narsize=128224",
    },
    "/nix/store/x2zjc47pkhcwxr4iyv5xj3hdqfzfnyd9-pcre2-10.46": {
        "nar_size": 2057672,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "ef951274a6ad882ad67a4e44a9fbe0600b0885cf5f6156217d976c2cf2cac467",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIF4MUjtX_Iq7-rDrGbPwkk0Fv-uMm5q_qwZyyMiYPp4EGCI?narsize=2057672",
    },
    "/nix/store/xakkd7mhg6dindq35ji8smr4j9ypwpn7-mailcap-2.1.54": {
        "nar_size": 119360,
        "references": [
        ],
        "sha256": "ff6a647601caa1d1032e49d844e9ee48dd05d7b9be059e00ca63b9d6f06972f5",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIC9aamNatQuyOhfmlv8fKrh0SxG8NXaeAjdVuZdXx1leGBI?narsize=119360",
    },
    "/nix/store/xcnqqnhw9hb4j5rjgds2yjryi8qki5f3-gcc-wrapper-15.2.0": {
        "nar_size": 69640,
        "references": [
            "/nix/store/521dd0054ifhzmjfmpx9mz0hr7wh7sig-glibc-2.42-67-bin",
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/aagixdk8hcs7p107szv9z17p87mx33nb-expand-response-params",
            "/nix/store/hngmi01i8wgi25a0byrxcn4ysz5j79mw-gcc-15.2.0-lib",
            "/nix/store/q5wv2ldpcv5w8yb2wmsngsygvlxb73fk-glibc-2.42-67-dev",
            "/nix/store/sq0nrnfwhkc5ljvklnrk5ps4358g4nbj-gcc-15.2.0",
            "/nix/store/sr26flm2nkfa12dkrwj2630kqsfakky4-coreutils-9.11",
            "/nix/store/w8xlvapzxcz23ba312q119p57bnc7200-gnugrep-3.12",
            "/nix/store/z4zcd87nx2hrsdayd0vl2mx5ncj3ikd8-binutils-wrapper-2.46",
            "/nix/store/zh1ijdhb6gng1509b1zrilb6xlzx60j6-bash-5.3p9",
        ],
        "sha256": "11ee28ef6c8aa3bf6902460ab0d17c561be688f0d3633d75b29a82bda512abbd",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIDbZuQHOPJfbZmL1qGRyFCM63v8SX5fXgLD7iwkUDI1NGFY?narsize=69640",
    },
    "/nix/store/xnlpfhi3m3in4b1h8h905hpv97gc8b07-mpdecimal-4.0.1": {
        "nar_size": 226192,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "ccd32eb9350b30bce21d151bc9a02c0a149bd5590621fbeaad823a4c7c47509b",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSINT_uL5NlFZRvhfjaHsd-EYmRBfKmkkzmq4Y3r4kSFy5GBQ?narsize=226192",
    },
    "/nix/store/y4h9ak6f3z22hvq97jwh90lmc4agx28c-binutils-2.46-lib": {
        "nar_size": 3018256,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/dbz6pb9g67kpgpl95k8d85kzpxm1c32p-zlib-1.3.2",
        ],
        "sha256": "eb0a63de220e8817d381c3dc0110221118e9b46635a6697856c448dbe89440ee",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIOAbGPcgCMSadJghPQHZ7qahGyf1wveNz5ZYPz1Ni5mIGCo?narsize=3018256",
    },
    "/nix/store/ylirzjzp6fxm8xdp8547kbbshbwydxs2-libmicrohttpd-1.0.2": {
        "nar_size": 266632,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/z49s8zpdckv2jbl1kbzdhl48z3f7hqv7-gnutls-3.8.13",
        ],
        "sha256": "b0f6980f14bc70659048417df4d75f11cd98e06d6c551693d2f24c7199566a29",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIGi0mRYmTsLLK9KQqbL0JArVnEthuWpI-PnfKKxlCdJzGAo?narsize=266632",
    },
    "/nix/store/z49s8zpdckv2jbl1kbzdhl48z3f7hqv7-gnutls-3.8.13": {
        "nar_size": 3732752,
        "references": [
            "/nix/store/0zc8py7pvw9wbfyym6204ddam722w7rj-gmp-with-cxx-6.3.0",
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/d3y9krrxjz9xyrwfr2f71d1yk6ck95yx-p11-kit-0.26.2",
            "/nix/store/hngmi01i8wgi25a0byrxcn4ysz5j79mw-gcc-15.2.0-lib",
            "/nix/store/ipz4lbivx3q7gr79130d6g5ix35vibnw-libunistring-1.4.2",
            "/nix/store/kh4j2kji7i38viz4h0cf6kbv9fnvhnkg-unbound-1.25.1-lib",
            "/nix/store/mbbchsqa44gcx16skf6v6c6bqiayamc9-dns-root-data-2025-04-14",
            "/nix/store/qa77jydj4h1n2lj4gzshrmkvinkaz3y1-libtasn1-4.21.0",
            "/nix/store/v9c75y1hd6yzlgiwvxriigylqgznq3rg-nettle-3.10.2",
            "/nix/store/zlvydh6q1rv1jza79b21yhi07ic0dkkg-libidn2-2.3.8",
        ],
        "sha256": "e4e0fd9b977aab05c8868ede0180ee9c3f2eb16d9f4e2f7fe17aee9f8f036d12",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSIEJ4HGiNpvlYlXcTEG5ZNlwnP9JoqmWiSi-WMmqzKsALGIoB?narsize=3732752",
    },
    "/nix/store/z4zcd87nx2hrsdayd0vl2mx5ncj3ikd8-binutils-wrapper-2.46": {
        "nar_size": 56616,
        "references": [
            "/nix/store/39lyf5g2iz4jd2r6q4g5whk9vw09zglj-binutils-2.46",
            "/nix/store/521dd0054ifhzmjfmpx9mz0hr7wh7sig-glibc-2.42-67-bin",
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
            "/nix/store/aagixdk8hcs7p107szv9z17p87mx33nb-expand-response-params",
            "/nix/store/q5wv2ldpcv5w8yb2wmsngsygvlxb73fk-glibc-2.42-67-dev",
            "/nix/store/sr26flm2nkfa12dkrwj2630kqsfakky4-coreutils-9.11",
            "/nix/store/zh1ijdhb6gng1509b1zrilb6xlzx60j6-bash-5.3p9",
        ],
        "sha256": "ccc130005a667edfae4e6c924b04e706fd5aa4d5188bed4e6d83c5427ceb1238",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIPQzAMk0hFHu2La8pT1dOZVUai_XWKOSHAraWJow1SzhGEA?narsize=56616",
    },
    "/nix/store/zh1ijdhb6gng1509b1zrilb6xlzx60j6-bash-5.3p9": {
        "nar_size": 1856848,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "8917ab69cca6f61b3090afa3c535687cb0960812fc3a78c3ebf5b38c05013310",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIA5MWdOGw-4Kz0BS3OFznIQOqV5YH8O0nV0OYsOt5Sy7GF4?narsize=1856848",
    },
    "/nix/store/zkw0hl5pzwkmrvkrfvr1q5zlk28nv9v2-gmp-6.3.0": {
        "nar_size": 739864,
        "references": [
            "/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67",
        ],
        "sha256": "3687bb297663fcba5a9301e250b23c5cb16ae17bfb649f425f98ef4847cd878c",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIJtyj-ncUuBRZMZnMSkyIX-tyU9VkGOB1ayerRejgb86GAo?narsize=739864",
    },
    "/nix/store/zlvydh6q1rv1jza79b21yhi07ic0dkkg-libidn2-2.3.8": {
        "nar_size": 368176,
        "references": [
            "/nix/store/ipz4lbivx3q7gr79130d6g5ix35vibnw-libunistring-1.4.2",
        ],
        "sha256": "8c43ed6d0f82da8be3c66ea79c09c30f32f03eb669ea16937108c6dd1e8d9095",
        "url": "https://nixos.snix.store/nar/snix-castore/CiUSINpTN1T22qy6QTQxyos6f0Q_qfn_nQHl4_DR7F07S3QcGKoB?narsize=368176",
    },
    "/nix/store/zs5bzwnkhgzka1ccvzkhx0xzf1mlah2j-coreutils-9.11-info": {
        "nar_size": 1059840,
        "references": [
        ],
        "sha256": "85682bb3219efde5fa54172c0412a74640aa1cf813c8489066d33a6fc9a3a379",
        "url": "https://nixos.snix.store/nar/snix-castore/CiQSIORr3VM6fFTkjg9EXe5HjqfTzEdXLOzQBq9smTtONzpjGAY?narsize=1059840",
    },
}
