#!/usr/bin/env bash
# Second RE backend: Buildbarn (bb-deployments docker-compose).
# Allow-failure lane until proven (PLAN-v2 acceptance rule) — EXCEPT the
# symlink round-trip, which is the lane's decisive first assertion: if the
# backend comes up, that check is hard. REv2 makes absolute-symlink
# handling a per-server capability (symlink_absolute_path_strategy), so
# variant C's verdict stays CONDITIONAL until this lane is green.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

BB_REV=${BB_REV:-master}
WORK=/tmp/bb-deployments
if [ ! -d "$WORK" ]; then
    git clone --depth 1 https://github.com/buildbarn/bb-deployments "$WORK"
fi

command -v docker >/dev/null || { echo "SKIP: docker not available"; exit 1; }

pushd "$WORK/docker-compose" >/dev/null
docker compose up -d
popd >/dev/null
trap 'cd "$WORK/docker-compose" && docker compose down -v >/dev/null 2>&1 || true' EXIT

for _ in $(seq 60); do
    (echo >/dev/tcp/127.0.0.1/8980) 2>/dev/null && break
    sleep 2
done

# Worker platform properties: extract from the deployment so buck2's
# actions match (Buildbarn requires exact platform equality).
PROPS=$(grep -rh "container-image" "$WORK/docker-compose" | head -1 || true)
echo "worker container-image hint: ${PROPS:-none found}"

if [ -e .buckconfig.local ]; then
    grep -q '@generated by tests/re-' .buckconfig.local && rm .buckconfig.local
fi
cat > .buckconfig.local <<'EOF'
# @generated by tests/re-buildbarn.sh -- removed on exit
[buck2]
  digest_algorithms = SHA256

[buck2_re_client]
  engine_address = grpc://127.0.0.1:8980
  action_cache_address = grpc://127.0.0.1:8980
  cas_address = grpc://127.0.0.1:8980
  tls = false
  instance_name = fuse
EOF
trap 'rm -f .buckconfig.local; cd "$WORK/docker-compose" && docker compose down -v >/dev/null 2>&1 || true' EXIT

buck2 --isolation-dir bb kill >/dev/null 2>&1 || true
rm -rf buck-out/bb

# HARD GATE: symlink round-trip through this backend, first.
if ! buck2 --isolation-dir bb build --config-file tests/re-demo/re.bcfg \
    tests//symlink-roundtrip:s2-read-remote tests//symlink-roundtrip:s2-read-local; then
    echo "BUILDBARN LANE FAILED at bring-up/round-trip build"
    exit 1
fi
RM=$(buck2 --isolation-dir bb build --config-file tests/re-demo/re.bcfg tests//symlink-roundtrip:s2-read-remote --show-full-output 2>/dev/null | awk '{print $2}')
RL=$(buck2 --isolation-dir bb build --config-file tests/re-demo/re.bcfg tests//symlink-roundtrip:s2-read-local --show-full-output 2>/dev/null | awk '{print $2}')
diff "$RM" "$RL" || { echo "BUILDBARN LANE FAILED: symlink round-trip mismatch (variant C invalid on this backend)"; exit 1; }
echo "symlink round-trip on Buildbarn: bit-exact"

# Rest of the lane (soft within allow-failure job): the example builds.
buck2 --isolation-dir bb build --config-file tests/re-demo/re.bcfg \
    root//examples/hello_c:main root//examples/tls_demo:main || {
    echo "BUILDBARN LANE: round-trip OK but example builds failed (see logs)"
    exit 1
}
echo "BUILDBARN LANE PASSED"
