#!/usr/bin/env bash
# Remote-execution demo: build the C examples against a local NativeLink
# (CAS + scheduler + worker) whose worker runs inside a namespace where
# /nix is masked read-only -- a genuinely store-less RE worker. Compile and
# link actions execute remotely (through the shim's chroot fallback);
# dirlir plan/materialize/import actions stay local, as designed.
#
# Run from the devshell: nix develop -c ./tests/re-demo.sh
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

NL_VERSION=1.5.2
NL_BIN=/tmp/nativelink-$NL_VERSION
if [ ! -x "$NL_BIN" ]; then
    echo "=== downloading nativelink v$NL_VERSION (static musl binary)"
    tmp=$(mktemp -d)
    curl -sL "https://github.com/TraceMachina/nativelink/releases/download/v$NL_VERSION/nativelink-$NL_VERSION-x86_64-unknown-linux-musl.tar.gz" |
        tar -xz -C "$tmp"
    install -m755 "$tmp/nativelink" "$NL_BIN"
    rm -rf "$tmp"
fi

if [ -e .buckconfig.local ]; then
    if grep -q '@generated by tests/re-demo.sh' .buckconfig.local; then
        rm .buckconfig.local  # leftover from an earlier aborted run
    else
        echo "error: .buckconfig.local exists; refusing to overwrite" >&2
        exit 1
    fi
fi

# Resolve host-side artifact paths with the DEFAULT daemon before writing
# .buckconfig.local: the RE settings change materializer state, which a
# running daemon refuses to pick up.
SHIM_HOST=$(buck2 build root//nix:dirlir-tools --show-full-output 2>/dev/null | awk '{print $2}')/bin/dirlir-shim
# The RE client is constructed from the daemon's startup buckconfig;
# --config-file cannot reach it, so drop the settings in .buckconfig.local
# for the duration of the demo.
cat > .buckconfig.local <<'EOF'
# @generated by tests/re-demo.sh -- removed on exit
[buck2]
  digest_algorithms = SHA256

[buck2_re_client]
  engine_address = grpc://127.0.0.1:50051
  action_cache_address = grpc://127.0.0.1:50051
  cas_address = grpc://127.0.0.1:50051
  tls = false
  instance_name = main
EOF
trap 'rm -f .buckconfig.local' EXIT

echo "=== starting nativelink (worker namespace has /nix masked read-only)"
rm -rf /tmp/nativelink-dirlir
mkdir -p /tmp/nativelink-dirlir
# Reset the RE isolation dir: its daemon state remembers artifacts as
# remotely-available, but this script wipes the NativeLink CAS on every
# run -- stale state would make buck2 fail re-uploading inputs it never
# downloaded (deferred materialization).
buck2 --isolation-dir re kill >/dev/null 2>&1 || true
rm -rf buck-out/re

# Outer ns (root-mapped, has caps): mask /nix. Inner ns: re-map back to the
# real non-zero uid -- a worker running as "root" drops spawned actions to
# an UNMAPPED nobody uid, and unmapped uids cannot create user namespaces
# (the shim's unshare EPERMs). The inner remap must be done by our own
# static shim: with /nix masked, no host binary (unshare included) exists.
unshare -rm bash -c \
    'mount -t tmpfs -o ro none /nix && exec "$1" --map-user "$2" --map-group "$3" -- "$4" "$5"' \
    outer "$SHIM_HOST" "$(id -u)" "$(id -g)" "$NL_BIN" tests/re-demo/nativelink.json5 \
    >/tmp/nativelink-dirlir/nativelink.log 2>&1 &
NL_PID=$!
trap 'rm -f .buckconfig.local; kill $NL_PID 2>/dev/null || true; buck2 --isolation-dir re kill >/dev/null 2>&1 || true' EXIT


for _ in $(seq 60); do
    if (echo >/dev/tcp/127.0.0.1/50051) 2>/dev/null; then break; fi
    if ! kill -0 $NL_PID 2>/dev/null; then
        echo "nativelink died on startup:"
        tail -20 /tmp/nativelink-dirlir/nativelink.log
        exit 1
    fi
    sleep 0.5
done
sleep 1  # let the worker register with the scheduler

buck2re() { buck2 --isolation-dir re "$@"; }

echo "=== building via remote execution (fresh isolation dir)"
buck2re build --config-file tests/re-demo/re.bcfg \
    root//examples/hello_c:main root//examples/tls_demo:main

echo "=== executor breakdown (what-ran):"
buck2re log what-ran 2>/dev/null | awk -F'\t' '{print $3, $2}' |
    sed -E 's/ \(.*\(/ /; s/\)$//' | awk '{print $1, $NF}' | sort | uniq -c | sort -rn

RE_COUNT=$(buck2re log what-ran 2>/dev/null | awk -F'\t' '$3 ~ /^re/' | wc -l)
LOCAL_MAT=$(buck2re log what-ran 2>/dev/null | awk -F'\t' '$3 == "local"' | grep -c dirlir_ || true)
echo "=== remote actions: $RE_COUNT, local dirlir actions: $LOCAL_MAT"

out_of() { buck2re build --config-file tests/re-demo/re.bcfg "$1" --show-full-output 2>/dev/null | awk '{print $2}'; }
SHIM=$(out_of root//nix:dirlir-tools)/bin/dirlir-shim
CXXLAYER=$(out_of root//layers:cxx-toolchain)
OPENSSL=$(out_of root//layers:openssl)

echo "=== running remotely-built binaries through the shim:"
"$SHIM" --store "$CXXLAYER/nix/store" -- "$(out_of root//examples/hello_c:main)"
"$SHIM" --store "$CXXLAYER/nix/store" --store "$OPENSSL/nix/store" -- "$(out_of root//examples/tls_demo:main)"

if [ "$RE_COUNT" -gt 0 ]; then
    echo "RE DEMO PASSED ($RE_COUNT actions executed remotely)"
else
    echo "RE DEMO FAILED: no actions executed remotely"
    exit 1
fi
